import { useState } from 'react'
import { Link } from 'react-router-dom'
import { collection, getArtists } from '../index'
import AlbumCard from '../components/AlbumCard'

/**
 * MusicPage — browse-only grid of album covers from the synced collection.
 *
 * Data comes from collection.json (generated by `npm run sync:music`).
 * No runtime API calls — everything is static and bundled at build time.
 */
function MusicPage() {
  const [sortBy, setSortBy] = useState('artist') // 'artist' | 'year' | 'album'
  const [filterArtist, setFilterArtist] = useState('')

  // Empty state — collection.json hasn't been generated yet
  if (!collection || collection.length === 0) {
    return (
      <div className="pa4 mw7 center">
        <p className="f6 mb4">
          <Link to="/" className="blue underline hover-no-underline">← back home</Link>
        </p>
        <h1 className="f3 near-black mb3">Music</h1>
        <p className="f5 gray lh-copy">
          No albums synced yet. Run <code className="f6 bg-light-gray ph1 pv1 br1">npm run sync:music</code> to
          pull your collection from Google Drive.
        </p>
      </div>
    )
  }

  // Build artist list for the filter dropdown
  const artists = getArtists()

  // Apply filtering
  const filtered = filterArtist
    ? collection.filter((a) => a.artist === filterArtist)
    : collection

  // Apply sorting
  const sorted = [...filtered].sort((a, b) => {
    if (sortBy === 'artist') {
      const cmp = (a.artist || '').localeCompare(b.artist || '')
      if (cmp !== 0) return cmp
      return (a.year || 0) - (b.year || 0)
    }
    if (sortBy === 'year') {
      return (b.year || 0) - (a.year || 0) // newest first
    }
    // 'album'
    return (a.album || '').localeCompare(b.album || '')
  })

  return (
    <div className="pa4 mw7 center">
      {/* Navigation */}
      <p className="f6 mb4">
        <Link to="/" className="blue underline hover-no-underline">← back home</Link>
      </p>

      {/* Header */}
      <h1 className="f3 near-black mb1">Music</h1>
      <p className="f6 gray mb4">
        {collection.length} album{collection.length !== 1 ? 's' : ''}
        {artists.length > 1 && ` from ${artists.length} artists`}
      </p>

      {/* Controls — sort and filter */}
      <div className="flex flex-wrap items-center mb4 gap2">
        <div className="mr3 mb2">
          <label className="f7 gray db mb1" htmlFor="sort-select">Sort by</label>
          <select
            id="sort-select"
            className="f6 pa1 ba b--light-gray bg-white"
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value)}
          >
            <option value="artist">Artist</option>
            <option value="year">Year</option>
            <option value="album">Album</option>
          </select>
        </div>

        {artists.length > 1 && (
          <div className="mb2">
            <label className="f7 gray db mb1" htmlFor="artist-filter">Filter by artist</label>
            <select
              id="artist-filter"
              className="f6 pa1 ba b--light-gray bg-white"
              value={filterArtist}
              onChange={(e) => setFilterArtist(e.target.value)}
            >
              <option value="">All artists</option>
              {artists.map((artist) => (
                <option key={artist} value={artist}>{artist}</option>
              ))}
            </select>
          </div>
        )}
      </div>

      {/* Album grid — responsive: 1 col mobile, 2 tablet, 3 desktop */}
      <div className="flex flex-wrap nl3 nr3">
        {sorted.map((album) => (
          <div key={album.slug} className="w-100 w-50-ns w-third-l ph3">
            <AlbumCard album={album} />
          </div>
        ))}
      </div>

      {/* Footer */}
      {filtered.length === 0 && filterArtist && (
        <p className="f6 gray tc mt4">No albums match that filter.</p>
      )}
    </div>
  )
}

export default MusicPage
