/**
 * Music collection data loader.
 *
 * collection.json is generated by `npm run sync:music` and gitignored.
 * It contains album metadata + Vercel Blob URLs for cover art.
 * Vite bundles it at build time, so there are no runtime API calls.
 *
 * We use import.meta.glob instead of a direct import so the build succeeds
 * even when collection.json hasn't been generated yet (returns empty array).
 * This mirrors how src/notes/index.js handles content loading.
 */

// import.meta.glob returns an empty object if no files match — no build errors
const collectionModules = import.meta.glob('./collection.json', { eager: true })
const rawCollection = collectionModules['./collection.json']?.default || []

/**
 * The full album collection, sorted by artist then year (set by the sync script).
 * Each album: { slug, album, artist, year, genre, coverUrl, trackCount, tracks }
 */
export const collection = rawCollection

/**
 * Get a single album by slug.
 */
export const getAlbumBySlug = (slug) =>
  collection.find((album) => album.slug === slug) || null

/**
 * Get all unique artists in the collection.
 */
export const getArtists = () =>
  [...new Set(collection.map((a) => a.artist))].sort()

/**
 * Get all unique genres in the collection (excluding nulls).
 */
export const getGenres = () =>
  [...new Set(collection.map((a) => a.genre).filter(Boolean))].sort()

/**
 * Filter albums by artist name (case-insensitive partial match).
 */
export const filterByArtist = (artist) =>
  collection.filter((a) =>
    a.artist.toLowerCase().includes(artist.toLowerCase())
  )

/**
 * Filter albums by genre (case-insensitive exact match).
 */
export const filterByGenre = (genre) =>
  collection.filter((a) =>
    a.genre && a.genre.toLowerCase() === genre.toLowerCase()
  )
